// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuCsKxLpX84DdiaKKXmQzSZ42JX4S8hqU',
    appId: '1:410569715478:web:feddc53f141b10b9892a37',
    messagingSenderId: '410569715478',
    projectId: 'myapp-3bf81',
    authDomain: 'myapp-3bf81.firebaseapp.com',
    storageBucket: 'myapp-3bf81.appspot.com',
    measurementId: 'G-JBZ3MP4ZDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAddwHvnJ0ez1RhSUGzFWcqGdrrD7PGkXM',
    appId: '1:410569715478:android:07d2f7fff90de0a5892a37',
    messagingSenderId: '410569715478',
    projectId: 'myapp-3bf81',
    storageBucket: 'myapp-3bf81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4FJwS_PnOO03U_dZxt80Dy4a0dWICD7I',
    appId: '1:410569715478:ios:1adeae51afa6bf57892a37',
    messagingSenderId: '410569715478',
    projectId: 'myapp-3bf81',
    storageBucket: 'myapp-3bf81.appspot.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4FJwS_PnOO03U_dZxt80Dy4a0dWICD7I',
    appId: '1:410569715478:ios:42884a79a530c98c892a37',
    messagingSenderId: '410569715478',
    projectId: 'myapp-3bf81',
    storageBucket: 'myapp-3bf81.appspot.com',
    iosBundleId: 'com.example.brewCrew.RunnerTests',
  );
}
